### ISSUE TITLE
"Should have at least 1 items" If Settings Are Incorrect

### ISSUE THREAD

**Issue by adamdabbracci** [awslabs/video-on-demand-on-aws#1]
When running the MediaConvert template, the following error gets thrown if your preset choices aren't correct of if you leave one empty (if you dont want DASH, for example):
```
Error
"BadRequestException"
Cause
{
  "errorMessage": "/outputGroups/0/outputs: Should have at least 1 items",
  "errorType": "BadRequestException",
  "stackTrace": [
    "Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)",
    "Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)",
    "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
    "Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
    "Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
    "Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
    "AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
    "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"
  ]
}
```

For example, if you exclude one:
```
. . .
MP4:
    Description: Specify the Mp4 presets to be used, leave blank to disable
    Type: String
    Default: "720"

  HLS:
    Description: Specify the Hls presets to be used, leave blank to disable
    Type: String
    Default: "1080,720,540,360,270"

  DASH:
    Description: Specify the Dash presets to be used, leave blank to disable
    Type: String
    Default: ""
. . .
```

or enter an invalid choice (270 isn't a preset for MP4):

```
. . .
MP4:
    Description: Specify the Mp4 presets to be used, leave blank to disable
    Type: String
    Default: "270"

  HLS:
    Description: Specify the Hls presets to be used, leave blank to disable
    Type: String
    Default: "1080,720,540,360,270"

  DASH:
    Description: Specify the Dash presets to be used, leave blank to disable
    Type: String
    Default: "720"
. . .
```

The step functions for the ingest process (`stackname-Process`) sends the following inputs to the Lambda that calls `process/media-convert-encode.js`. 
```
{
  "guid": "4ed0adb8-4609-4e53-9e4e-d9587d04d764",
  "startTime": "2018-03-15 23:18.9",
  "workflowStatus": "ingest",
  "frameCapture": false,
  "mp4": [
    270
  ],
  "srcVideo": "source.mp4",
  "srcBucket": "STACK-source-fjgtig8f0qyl",
  "mp4Bucket": "STACK-mp4destination-864x0xmc99nb",
  "abrBucket": "STACK-abrdestination-svrx46v74rkl",
  "hls": [
    720
  ],
  "dash": [
    720
  ],
  "srcHeight": 720,
  "srcWidth": 1280
}
```

The process then checks each type of video output defined in the templates and tries to create an output group for the job. If the presets are empty or invalid, the following lines will insert an empty OutputGroup to the Outputs array for each preset:
https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/process/media-convert-encode.js#L236
https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/process/media-convert-encode.js#L288
https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/process/media-convert-encode.js#L344

I will try to get a bugfix in for this, but making sure the presets are correct will prevent this from happening :)
